name: Update Calendar

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write   # 👈 TO JE KLJUČNO

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install icalendar

      - run: python scripts/build_calendar.py

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add .
          git commit -m "auto update" || echo "no changes"
          git push
